[information]
name = "retrowave"
background = "dark"
author = 'Milianor'

[palette]
fg = '#f8f8f8'
bg = '#262335'
alt_bg = '#241b2f'
currentline = '#463465'
selection = '#463465'
comment = '#495495'
cyan = '#61E2FF'
green = '#72f1b8'
orange = '#ff8b39'
pink = '#ff7edb'
purple = '#AF6DF9'
red = '#fe4450'
yellow = '#FFCC00'
cursor_fg = '#282a36'
cursor_bg = '#f8f8f8'
sign_add = '#72f1b8'
sign_change = '#ff8b39'
sign_delete = '#fe4450'
error = '#fe4450'
warning = '#ff8b39'
info = '#61E2FF'
hint = '#61E2FF'
other = '#AF6DF9'
blankline = '#57367C'
active_blankline = '#39785C'

[highlights]
Normal = 'fg bg'
SignColumn = '- bg'
MsgArea = 'link:Normal'
ModeMsg = 'fg bg b'
MsgSeparator = 'fg bg b'
SpellBad = 'error - u'
SpellCap = 'info - u'
SpellLocal = 'warning - u'
SpellRare = 'other - u'
NormalNC = 'link:Normal'
Pmenu = 'link:NormalFloat'
PmenuSel = '- selection'
WildMenu = '- bg b'
CursorLineNr = 'cyan bg'
Comment = 'comment - i'
Folded = 'comment selection'
FoldColumn = 'fg bg'
LineNr = 'comment bg'
FloatBorder = 'comment alt_bg'
Whitespace = 'bg -'
WinSeparator = 'comment alt_bg'
VertSplit = 'link:WinSeparator'
CursorLine = '- currentline'
CursorColumn = 'link:CursorLine'
ColorColumn = '- alt_bg'
NormalFloat = 'fg alt_bg'
Visual = '- selection'
VisualNOS = 'link:Visual'
WarningMsg = 'warning bg'
DiffAdd = 'sign_add - r'
DiffChange = 'sign_change - r'
DiffDelete = 'sign_delete - r'
QuickFixLine = '- selection b'
PmenuSbar = 'link:NormalFloat'
PmenuThumb = '- cyan'
MatchWord = '- - u'
MatchParen = 'hint bg u'
MatchWordCur = '- - u'
MatchParenCur = '- - u'
Cursor = 'cursor_fg cursor_bg'
lCursor = 'cursor_fg cursor_bg'
CursorIM = 'cursor_fg cursor_bg'
TermCursor = 'cursor_fg cursor_bg'
TermCursorNC = 'cursor_fg cursor_bg'
Conceal = 'pink'
Directory = 'cyan'
SpecialKey = 'yellow - b'
Title = 'cyan - b'
ErrorMsg = 'error'
Search = 'link:Visual'
IncSearch = 'cyan'
Substitute = 'link:IncSearch'
MoreMsg = 'cyan - b'
Question = 'cyan - b'
EndOfBuffer = 'bg'
NonText = 'comment'
Variable = 'fg'
String = 'orange'
Character = 'orange'
Constant = 'red'
Number = 'red'
Boolean = 'red'
Float = 'link:Number'
Identifier = 'yellow'
Function = 'link:Identifier'
Operator = 'pink'
Type = 'pink - i'
StorageClass = 'green'
Structure = 'green'
Typedef = 'green'
Keyword = 'green'
Statement = 'green'
Conditional = 'green'
Repeat = 'green'
Label = 'green'
Exception = 'green'
Include = 'green'
PreProc = 'green'
Define = 'green'
Macro = 'green'
PreCondit = 'green'
Special = 'yellow'
SpecialChar = 'yellow'
Tag = 'yellow'
Debug = 'green'
Delimiter = 'fg -'
SpecialComment = 'yellow'
Underlined = '- - u'
Bold = '- - b'
Italic = '- - i'
Ignore = 'purple bg b'
Todo = 'cyan - b'
Error = 'error - b'
TabLine = 'comment bg'
TabLineSel = 'link:Normal'
TabLineFill = '- bg'

[TreeSitter]
'@comment' = 'link:Comment'
'@comment.documentation' = 'link:Comment'
'@error' = 'link:Error'
'@operator' = 'link:Operator'
'@punctuation.delimiter' = 'fg'
'@punctuation.delimiter.cpp' = 'cyan'
'@punctuation.delimiter.yaml' = 'cyan'
'@punctuation.bracket' = 'purple'
'@punctuation.special' = 'purple'
'@string' = 'link:String'
'@string.regex' = 'red'
'@string.escape' = 'purple'
'@string.special' = 'purple'
'@character' = 'link:@string'
'@character.special' = 'yellow'
'@function' = 'link:Function'
'@function.builtin' = 'link:@function'
'@function.call' = 'link:@function'
'@method' = 'link:@function'
'@method.call' = 'link:@function'
'@constructor' = 'purple'
'@constructor.c_sharp' = 'link:@type'
'@constructor.php' = 'link:@type'
'@constructor.tsx' = 'green'
'@constructor.javascript' = 'green'
'@parameter' = 'orange - i'
'@boolean' = 'link:Boolean'
'@number' = 'link:Number'
'@float' = 'link:Float'
'@label.json' = 'cyan'
'@label.ruby' = 'link:@variable.builtin'
'@exception' = 'link:Exception'
'@type' = 'link:Type'
'@type.dart' = 'link:@type'
'@type.builtin' = 'link:Type'
'@type.builtin.cpp' = 'link:Type'
'@type.definition' = 'link:Type'
'@type.qualifier' = 'cyan'
'@storageclass' = 'cyan'
'@attribute' = 'yellow - i'
'@field' = 'cyan'
'@field.yaml' = 'cyan'
'@property' = 'link:@field'
'@property.css' = 'cyan'
'@variable' = 'fg'
'@variable.builtin' = 'purple - i'
'@variable.global.ruby' = 'link:@constant'
'@constant' = 'link:Constant'
'@constant.builtin' = 'link:Constant'
'@constant.macro' = 'link:Constant'
'@namespace' = 'fg'
'@symbol' = 'purple'
'@text' = 'fg'
'@text.strong' = 'orange - b'
'@text.emphasis' = 'green - i'
'@text.strike' = 'yellow - s'
'@text.title' = 'cyan - b'
'@text.literal' = 'link:@text'
'@text.quote' = 'yellow'
'@text.uri' = 'cyan'
'@text.math' = 'cyan'
'@text.reference' = 'cyan'
'@text.todo' = 'link:Todo'
'@text.warning' = 'link:WarningMsg'
'@text.danger' = 'link:ErrorMsg'
'@text.diff.add' = 'link:DiffAdd'
'@text.diff.delete' = 'link:DiffDelete'
'@tag' = 'green'
'@tag.attribute' = 'link:@field'
'@tag.delimiter' = 'cyan'

[Semantic]
'@lsp.type.namespace' = 'link:@namespace'
'@lsp.type.type' = 'link:@type'
'@lsp.type.typeParameter' = 'link:@type'
'@lsp.type.class' = 'link:@type'
'@lsp.type.enum' = 'link:@type'
'@lsp.type.interface' = 'link:@type'
'@lsp.type.struct' = 'link:Structure'
'@lsp.type.parameter' = 'link:@parameter'
'@lsp.type.variable' = 'link:@variable'
'@lsp.type.variable.lua' = '- -'
'@lsp.type.property' = 'link:@property'
'@lsp.type.enumMember' = 'link:@constant'
'@lsp.type.function' = 'link:@function'
'@lsp.type.method' = 'link:@method'
'@lsp.type.macro' = 'link:@macro'
'@lsp.type.decorator' = 'link:@function'
'@lsp.typemod.variable.defaultLibrary' = 'link:@constant'
'@lsp.typemod.parameter.readyonly' = 'link:Italic'
'@lsp.typemod.variable.readonly' = 'link:@constant'
'@lsp.typemod.variable.global' = 'link:@constant'
'@lsp.typemod.keyword.documentation' = 'link:@keyword'
'@lsp.typemod.class.documentation' = 'link:@type'
'@lsp.typemod.property.readonly' = 'link:@constant'  

[Whichkey]
WhichKey = 'fg'
WhichKeySeparator = 'cyan'
WhichKeyGroup = 'green'
WhichKeyDesc = 'cyan'
WhichKeyFloat = 'link:NormalFloat'

[Git]
SignAdd = 'sign_add'
SignChange = 'sign_change'
SignDelete = 'sign_delete'
GitSignsAdd = 'sign_add'
GitSignsChange = 'sign_change'
GitSignsDelete = 'sign_delete'
GitSignsAddInline = 'green'
GitSignsChangeInline = 'orange'
GitSignsDeleteInline = 'red'

[Illuminate]
illuminatedWord = '- selection'
illuminatedCurWord = 'link:illuminatedWord'
IlluminatedWordText = 'link:illuminatedWord'
IlluminatedWordRead = 'link:illuminatedWord'
IlluminatedWordWrite = 'link:illuminatedWord'

[LSP]
LspDiagnosticsDefaultError = 'error'
LspDiagnosticsDefaultWarning = 'warning'
LspDiagnosticsDefaultInformation = 'info'
LspDiagnosticsDefaultInfo = 'info'
LspDiagnosticsDefaultHint = 'hint'
LspDiagnosticsVirtualTextError = 'error'
LspDiagnosticsVirtualTextWarning = 'warning'
LspDiagnosticsVirtualTextInformation = 'info'
LspDiagnosticsVirtualTextInfo = 'info'
LspDiagnosticsVirtualTextHint = 'hint'
LspDiagnosticsFloatingError = 'error'
LspDiagnosticsFloatingWarning = 'warning'
LspDiagnosticsFloatingInformation = 'info'
LspDiagnosticsFloatingInfo = 'info'
LspDiagnosticsFloatingHint = 'hint'
DiagnosticHint = 'hint'
DiagnosticInfo = 'info'
DiagnosticError = 'error'
DiagnosticOther = 'other'
DiagnosticVirtualTextHint = 'hint'
DiagnosticVirtualTextInfo = 'info'
DiagnosticVirtualTextWarn = 'warning'
DiagnosticVirtualTextError = 'error'
DiagnosticFloatingHint = 'hint'
DiagnosticFloatingInfo = 'info'
DiagnosticFloatingWarn = 'warning'
DiagnosticFloatingError = 'error'
DiagnosticUnderlineHint = 'hint'
DiagnosticUnderlineInfo = 'info'
DiagnosticUnderlineWarn = 'warning'
DiagnosticUnderlineError = 'error'
DiagnosticSignError = 'error'
DiagnosticSignWarning = 'warning'
DiagnosticSignInformation = 'info'
DiagnosticSignInfo = 'info'
DiagnosticSignHint = 'hint'
DiagnosticSignOther = 'other'
LspDiagnosticsSignError = 'error'
LspDiagnosticsSignWarning = 'warning'
LspDiagnosticsSignInformation = 'info'
LspDiagnosticsSignInfo = 'info'
LspDiagnosticsSignHint = 'hint'
LspDiagnosticsError = 'error'
LspDiagnosticsWarning = 'warning'
LspDiagnosticsInformation = 'info'
LspDiagnosticsInfo = 'info'
LspDiagnosticsHint = 'hint'
LspDiagnosticsUnderlineError = '- - u'
LspDiagnosticsUnderlineWarning = '- - u'
LspDiagnosticsUnderlineInformation = '- - u'
LspDiagnosticsUnderlineInfo = '- - u'
LspDiagnosticsUnderlineHint = '- - u'
LspReferenceRead = '- selection'
LspReferenceText = '- selection'
LspReferenceWrite = '- selection'

[LspSaga]
SagaNormal = 'link:NormalFloat'
SagaWinbarModule = 'link:@namespace'
SagaWinbarInterface = 'link:@type'
SagaWinbarConstructor = 'link:@constructor'
SagaWinbarStruct = 'link:@structure'
SagaWinbarObject = 'link:@field'
SagaWinbarUnit = 'link:@number'
SagaWinbarFile = 'fg'
SagaWinbarSnippet = 'fg'
SagaWinbarText = 'link:@string'
SagaWinbarTypeAlias = 'link:@type'
SagaWinbarEvent = 'link:@function'
SagaWinbarParameter = 'link:@parameter'
SagaWinbarKey = 'link:@keyword'
SagaWinbarValue = 'fg'
SagaWinbarMacro = 'link:Macro'
SagaWinbarNumber = 'link:@number'
SagaWinbarConstant = 'link:@constant'
SagaWinbarFunction = 'link:@function'
SagaWinbarEnum = 'link:@type'
SagaWinbarField = 'link:@field'
SagaWinbarProperty = 'link:@property'
SagaWinbarMethod = 'link:@method'
SagaWinbarClass = 'link:@type'
SagaWinbarFolder = 'link:Directory'
SagaWinbarPackage = 'link:Directory'
SagaWinbarStaticMethod = 'link:@method'
SagaWinbarTypeParameter = 'link:@type'
SagaWinbarEnumMember = 'link:@constant'
SagaWinbarOperator = 'link:@operator'
SagaWinbarNull = 'link:@constant'
SagaWinbarNamespace = 'link:@namespace'
SagaWinbarArray = 'link:@keyword'
SagaWinbarBoolean = 'link:@boolean'
SagaWinbarString = 'link:@string'
SagaWinbarVariable = 'link:@variable'
SagaWinbarFilename = 'fg'
SagaWinbarFolderName = 'fg'
SagaWinbarFileIcon = 'link:Directory'
SagaWinbarSep = 'cyan'

[Telescope]
TelescopeTitle = 'cyan - r'
TelescopeNormal = 'link:NormalFloat'
TelescopeSelection = 'fg selection'
TelescopeSelectionCaret = 'cyan selection'
TelescopeMatching = 'link:IncSearch'
TelescopeBorder = 'link:WinSeparator'

[NvimTree]
NvimTreeRootFolder = 'link:Directory'
NvimTreeFolderIcon = 'link:Directory'
NvimTreeIndentMarker = 'link:Directory'
NvimTreeNormal = 'link:NormalFloat'
NvimTreeWinSeparator = 'alt_bg alt_bg'
NvimTreeVertSplit = 'link:VertSplit'
NvimTreeFolderName = 'fg'
NvimTreeOpenedFolderName = 'link:Directory'
NvimTreeEmptyFolderName = 'cyan - i'
NvimTreeGitIgnored = 'comment - i'
NvimTreeEndOfBuffer = 'alt_bg'
NvimTreeCursorLine = 'link:CursorLine'
NvimTreeGitStaged = 'sign_add'
NvimTreeGitNew = 'sign_add'
NvimTreeGitRenamed = 'sign_add'
NvimTreeGitDeleted = 'sign_delete'
NvimTreeGitMerge = 'sign_change'
NvimTreeGitDirty = 'sign_change'

[NeoTree]
NeoTreeNormal = 'link:NormalFloat'
NeoTreeNormalNC = 'link:NormalFloat'
NeoTreeEndOfBuffer = 'alt_bg'
NeoTreeRootName = 'link:Directory'
NeoTreeFileName = 'fg'
NeoTreeFileNameOpened = 'purple - b'
NeoTreeFloatBorder = 'link:WinSeparator'
NeoTreeFloatTitle = 'link:Title'
NeoTreeGitAdded = 'sign_add'
NeoTreeGitConflict = 'sign_change'
NeoTreeGitDeleted = 'sign_delete'
NeoTreeGitIgnored = 'comment - i'
NeoTreeGitModified = 'sign_change'
NeoTreeGitUnstaged = 'sign_change'
NeoTreeGitUntracked = 'sign_change'
NeoTreeGitStaged = 'sign_add'
NeoTreeIndentMarker = 'comment'

[Dap]
DapUINormal = 'link:NormalFloat'

[StatusLine]
StatusLine = 'fg alt_bg'
StatusLineNC = 'alt_bg alt_bg'
StatusLineSeparator = 'alt_bg'
StatusLineTerm = 'alt_bg'
StatusLineTermNC = 'alt_bg'

[Dashboard]
DashboardHeader = 'red'
DashboardCenter = 'fg'
DashboardFooter = 'comment'
DashboardProjectTitle = 'link:Title'
DashboardProjectTitleIcon = 'link:Title'
DashboardProjectIcon = 'purple'
DashboardMruTitle = 'link:Title'
DashboardMruIcon = 'link:Title'
DashboardFiles = 'fg'
DashboardShotCutIcon = 'cyan'
DashboardDesc = 'cyan'
DashboardKey = 'purple'
DashboardIcon = 'cyan'
DashboardShotCut = 'purple'

[Cmp]
CmpItemAbbrDeprecated = 'comment - s'
CmpItemAbbrMatch = 'link:IncSearch' 
CmpItemAbbrMatchFuzzy = 'link:IncSearch' 
CmpItemKindText = 'link:@string'
CmpItemKindMethod = 'link:@method'
CmpItemKindFunction = 'link:@function'
CmpItemKindConstructor = 'link:@constructor'
CmpItemKindField = 'link:@field'
CmpItemKindVariable = 'link:@variable'
CmpItemKindClass = 'link:@type'
CmpItemKindInterface = 'link:@type'
CmpItemKindModule = 'link:@namespace'
CmpItemKindProperty = 'link:@property'
CmpItemKindUnit = 'link:@number'
CmpItemKindValue = 'link:@string'
CmpItemKindEnum = 'link:@type'
CmpItemKindKeyword = 'link:@keyword'
CmpItemKindSnippet = 'link:@keyword'
CmpItemKindColor = 'orange'
CmpItemKindFile = 'fg'
CmpItemKindReference = 'link:@text.reference'
CmpItemKindFolder = 'link:Directory'
CmpItemKindEnumMember = 'link:@constant'
CmpItemKindConstant = 'link:@constant'
CmpItemKindStruct = 'link:Structure'
CmpItemKindEvent = 'link:@function'
CmpItemKindOperator = 'link:@operator'
CmpItemKindTypeParameter = 'link:@type'

[Navic]
NavicIconsFile = 'fg'
NavicIconsModule = 'link:@namespace'
NavicIconsNamespace = 'link:@namespace'
NavicIconsPackage = 'link:Directory'
NavicIconsClass = 'link:@type'
NavicIconsMethod = 'link:@method'
NavicIconsProperty = 'link:@property'
NavicIconsField = 'link:@field'
NavicIconsConstructor = 'link:@constructor'
NavicIconsEnum = 'link:@type'
NavicIconsInterface = 'link:@type'
NavicIconsFunction = 'link:@function'
NavicIconsVariable = 'link:@Variable'
NavicIconsConstant = 'link:@constant'
NavicIconsString = 'link:@string'
NavicIconsNumber = 'link:@number'
NavicIconsBoolean = 'link:@boolean'
NavicIconsArray = 'link:@keyword'
NavicIconsObject = 'link:@keyword'
NavicIconsKey = 'link:@keyword'
NavicIconsNull = 'link:@constant'
NavicIconsEnumMember = 'link:@constant'
NavicIconsStruct = 'link:Structure'
NavicIconsEvent = 'link:@function'
NavicIconsOperator = 'link:@operator'
NavicIconsTypeParameter = 'link:@type'
NavicText = 'link:@text'
NavicSeparator = 'link:@keyword'

[Notify]
NotifyBackground = 'link:NormalFloat'
NotifyERRORBorder = 'error'
NotifyWARNBorder = 'warning'
NotifyINFOBorder = 'info'
NotifyDEBUGBorder = 'comment'
NotifyTRACEBorder = 'other'
NotifyERRORIcon = 'error'
NotifyWARNIcon = 'warning'
NotifyINFOIcon = 'info'
NotifyDEBUGIcon = 'comment'
NotifyTRACEIcon = 'other'
NotifyERRORTitle = 'error'
NotifyWARNTitle = 'warning'
NotifyINFOTitle = 'info'
NotifyDEBUGTitle = 'comment'
NotifyTRACETitle = 'other'
NotifyERRORBody = 'link:NormalFloat'
NotifyWARNBody = 'link:NormalFloat'
NotifyINFOBody = 'link:NormalFloat'
NotifyDEBUGBody = 'link:NormalFloat'
NotifyTRACEBody = 'link:NormalFloat'

[Neorg]
'@neorg.headings.1.title' = 'orange'
'@neorg.headings.2.title' = 'cyan'
'@neorg.headings.3.title' = 'green'
'@neorg.headings.4.title' = 'yellow'
'@neorg.headings.5.title' = 'red'
'@neorg.headings.6.title' = 'purple'
'@neorg.headings.1.prefix' = 'link:@neorg.headings.1.title'
'@neorg.headings.2.prefix' = 'link:@neorg.headings.2.title'
'@neorg.headings.3.prefix' = 'link:@neorg.headings.3.title'
'@neorg.headings.4.prefix' = 'link:@neorg.headings.4.title'
'@neorg.headings.5.prefix' = 'link:@neorg.headings.5.title'
'@neorg.headings.6.prefix' = 'link:@neorg.headings.6.title'
'@neorg.lists.ordered.1.prefix' = 'link:@neorg.headings.1.title'
'@neorg.lists.ordered.2.prefix' = 'link:@neorg.headings.2.title'
'@neorg.lists.ordered.3.prefix' = 'link:@neorg.headings.3.title'
'@neorg.lists.ordered.4.prefix' = 'link:@neorg.headings.4.title'
'@neorg.lists.ordered.5.prefix' = 'link:@neorg.headings.5.title'
'@neorg.lists.ordered.6.prefix' = 'link:@neorg.headings.5.title'
'@neorg.lists.unordered.1.prefix' = 'link:@neorg.lists.ordered.1.prefix'
'@neorg.lists.unordered.2.prefix' = 'link:@neorg.lists.ordered.2.prefix'
'@neorg.lists.unordered.3.prefix' = 'link:@neorg.lists.ordered.3.prefix'
'@neorg.lists.unordered.4.prefix' = 'link:@neorg.lists.ordered.4.prefix'
'@neorg.lists.unordered.5.prefix' = 'link:@neorg.lists.ordered.5.prefix'
'@neorg.lists.unordered.6.prefix' = 'link:@neorg.lists.ordered.6.prefix'
'@neorg.links.file' = 'link:@text.uri'

[IndentBlankLine]
IndentBlanklineChar = 'blankline'
IndentBlanklineContextChar = 'active_blankline'
IndentBlanklineSpaceChar = 'blankline'
IndentBlanklineContextSpaceChar = 'active_blankline'

[Hop]
HopNextKey = 'red - b'
HopNextKey1 = 'cyan - b'
HopUnmatched = 'comment'

[SymbolsOutline]
FocusedSymbol = 'cyan'
SymbolsOutlineConnector = 'comment'

[MiniCursor]
MiniCursorword = '- selection'

[MiniCompletion]
MiniCompletionActiveParameter = 'link:@paramter'

[MiniJump]
MiniJump2dSpot = 'cyan'
MiniJump2dSpotUnique = 'purple'

[MiniIndent]
MiniIndentscopeSymbol = 'cyan'
MiniIndentscopeSymbolOff = '- -'

[MiniMap]
MiniMapNormal = 'comment alt_bg'
MiniMapSymbolCount = 'purple'
MiniMapSymbolLine = 'cyan'
MiniMapSymbolView = 'alt_bg'

[MiniStatusLine]
MiniStatuslineModeNormal = 'bg cyan'
MiniStatuslineModeInsert = 'bg green'
MiniStatuslineModeVisual = 'bg purple'
MiniStatuslineModeReplace = 'bg red'
MiniStatuslineModeCommand = 'orange'
MiniStatuslineDevinfo = 'fg comment'
MiniStatuslineFileinfo = 'fg comment'

[MiniTabLine]
MiniTablineCurrent = 'fg comment'
MiniTablineVisible = 'fg comment'
MiniTablineHidden = 'comment bg'
MiniTablineModifiedCurrent = 'link:MiniTabLineCurrent'
MiniTablineModifiedVisible = 'link:MiniTablineVisible'
MiniTablineModifiedHidden =  'link:MiniTablineHidden'
MiniTablineFill = 'link:NormalFloat'
MiniTablineTabpagesection = 'link:NormalFloat'

[MiniStarter]
MiniStarterCurrent = 'link:CursorLine'
MiniStarterHeader = 'red'
MiniStarterFooter = 'comment'
MiniStarterItem = 'fg'
MiniStarterItemBullet = 'cyan'
MiniStarterItemPrefix = 'cyan'
MiniStarterSection = 'link:Title'
MiniStarterQuery = 'red - b'
